#+TITLE: String Basics
#+DATE:   2026 Mar 26
#+LANGUAGE: en
#+STARTUP: overview
#+TAGS: tutorial blog string programming
#+DESCRIPTION: String Tutorial

* Table of Contents                                                     :TOC:
- [[#string-basics][String Basics]]
- [[#substring][Substring]]
- [[#subsequence][Subsequence]]
- [[#subset][Subset]]
- [[#sublist][Sublist]]
- [[#reference][Reference]]

* String Basics

A string is traditionally a sequence of characters, either as a literal constant or as some kind of variable. The latter may allow its elements to be mutated and the length changed, or it may be fixed (after creation).

Some languages provide strings as a builtin datatype (Like *C++*, *Java*, *C#*) whereas some implement string as an array of characters (Like *C*).

Strings are not available in *C*. Instead, we use a char array to read strings, where the end of string is marked with the special character ='\0'= often called as null character.

When we have a /char/ =arr[]= in *C* and want to iterate over the characters with a loop like:

#+BEGIN_SRC c
for (int i = 0; i < strlen(arr); i++) {
    printf("%c", arr[i]);
}
#+END_SRC

⚠️ Problem:
Using strlen(arr) inside loop condition increases complexity.

- strlen(arr) itself = =O(n)=
- Loop runs =n= times
- Total complexity = =O(n^2)=

---

Optimized Version:

#+BEGIN_SRC c
int len = strlen(arr);

for (int i = 0; i < len; i++) {
    printf("%c", arr[i]);
}
#+END_SRC

Now complexity = =O(n)=

---

* Substring

A substring is a part of string =S[i : j]= such that =i ≤ j=.
It is a contiguous slice of the original string.

*Example* :
For S = "abc", substrings are:

1. *a*
2. *b*
3. *c*
4. *ab*
5. *bc*
6. *abc*

---

- Therefore, a string of length =N= contains =N * (N + 1)  / 2= substrings.

---

* Subsequence

A subsequence is a sequence that can be derived from another sequence by deleting some elements (/possibly zero but not all/) without changing the order of the remaining elements.

---

*Example* :
For S = "abc", subsequences are:

1. *a*
2. *b*
3. *c*
4. *ab*
5. *bc*
6. *ac*
7. *abc*

---

- Therefore, a sequence of size =N= contains =2^N - 1= subsequences.

---

* Subset

Subset is any unordered set of elements from the original list.

---

*Example* :
For S = "abc", subsets are:

1. ={}=
2. ={a}=
3. ={b}=
4. ={c}=
5. ={c, b}=
6. ={a, b}=
7. ={a, c}=
8. ={a, b, c}=

---

- Therefore, a set of size =N= contains =2^N= subsets.

---

*NOTE* :

- ={b, a, c}= is a subset of string ="abc"= but not a subsequence.
- Each subsequence of a collection of elements is its subset also, but reverse does not hold.

---

* Sublist

Sublist is any unordered list derived from the original list.

- Elements need not be unique
- Must exist on separate indices in the original list

 ---

* Reference

- [[https://www.hackerrank.com/challenges/anagram/topics/string-basics][HackerRank]]
